### ISSUE TITLE
Doesn't work in Safari Private Browsing

### ISSUE THREAD

**Issue by nabilfreeman** [simplyGits/reactive-local-storage#3]
Safari makes localStorage inaccessible in private mode.

Any ideas for workarounds?

**Comment by tkon99** [comment]
Not sure what @lieuwex's view is on this, but I personally used cookies in one of my projects to overcome this.

**Comment by lieuwex** [comment]
Good question, I think that indeed using cookies instead of localstorage in inPrivate mode is the solution here. 

You can use something like
```javascript
function isLocalStorageSupported() {
	if (!('localStorage' in window)) {
		return false;
	}

	const testKey = '_safari_test_';
	try {
		window.localStorage.setItem(testKey, '1');
		window.localStorage.removeItem(testKey);
	} catch (error) {
		return false;
	}

	return true;
}
```

to detect if localStorage works in the current browser.

Adding a polyfill-esque thing would be out of scope for this project, I think.

Hope this answers your question!
